---

- name: Create varnish environment file
  template:
    src: default.varnish.j2
    dest: "/etc/default/varnish-{{ item.name }}"
  with_items: 
    - "{{ varnish_application }}"
  notify:
    - restart varnish

- name: Create varnish environment file
  template:
    src: varnish.reload-vcl.j2
    dest: "/usr/share/varnish/reload-vcl-{{ item.name }}"
  with_items: 
    - "{{ varnish_application }}"

- name: Create varnishd systemd unit
  template:
    src: varnish.service.j2
    dest: /etc/systemd/system/varnish@.service
  notify:
    - reload systemd-unit

- name: Create varnishlog systemd unit
  template:
    src: varnishlog.service.j2
    dest: /etc/systemd/system/varnishlog@.service
  notify:
    - reload systemd-unit
    - stop varnishlog

- name: Get varnish configuration
  template:
    src: template.varnish.vcl.j2
    dest: "/etc/varnish/{{ item.name }}.vcl"
  with_items: 
    - "{{ varnish_application }}"
  notify: 
    - reload varnish

- name: Create consul-template systemd unit
  template:
    src: consul-template.service.j2
    dest: /etc/systemd/system/consul-template@.service
  notify:
    - enable consul-template
    - reload systemd-unit
  with_items: 
    - "{{ varnish_application }}"
  when: (use_consul)

- name: Get varnish configuration
  template:
    src: template.consul.varnish.vcl.j2
    dest: "/etc/varnish/{{ item.name }}.consul.vcl"
  with_items: 
    - "{{ varnish_application }}"
  #notify: 
  #  - restart consul-varnish
  when: (use_consul)
