---

- name: Create Varnish environment file
  template:
    src: default.varnish.j2
    dest: "/etc/default/varnish-{{ item.name }}"
  with_items: 
    - "{{ varnish_application }}"
  notify:
    - restart varnish

- name: Create Varnishd Systemd unit
  template:
    src: varnish.service.j2
    dest: /etc/systemd/system/varnish@.service
  notify:
    - reload systemd-unit

- name: Create Varnishlog Systemd unit
  template:
    src: varnishlog.service.j2
    dest: /etc/systemd/system/varnishlog@.service
  notify:
    - reload systemd-unit
    - restart varnishlog

- name: Get Varnish configuration
  template:
    src: template.varnish.vcl.j2
    dest: "/etc/varnish/{{ item.name }}.vcl"
  with_items: 
    - "{{ varnish_application }}"
  notify: 
    - restart varnish
