---

- name: Install varnish 5.x package
  apt:
    name: varnish
    state: latest
    update_cache: yes
  notify:
    - disable default varnish
    - disable default varnishlog
    - disable default varnishncsa
    - reload systemd-unit

- name: Install consul-template
  get_url:
    url: https://releases.hashicorp.com/consul-template/0.19.4/consul-template_0.19.4_linux_amd64.zip
    dest: /tmp/consul-template.zip
  notify:
    - unzip consul-template
  when: (use_consul)
