---

- name: Install Varnish 5.x package
  apt:
    name: varnish
    state: latest
    update_cache: yes
  notify:
    - start varnish

- name: Delete default varnish systemd unit
  file:
    path: /lib/systemd/system/varnish.service
    state: absent
  notify:
    - reload systemd-unit
