---

- name: Setup varnish repository key
  apt_key:
    url: https://packagecloud.io/varnishcache/varnish{{ varnish_version }}/gpgkey
    state: present

- name: Setup varnish repository
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.file }}"
    state: present
  with_items:
    - repo: "deb https://packagecloud.io/varnishcache/varnish{{ varnish_version }}/ubuntu/ {{ ansible_distribution_release }} main"
      file: "deb-varnish"
    - repo: "deb-src https://packagecloud.io/varnishcache/varnish{{ varnish_version }}/ubuntu/ {{ ansible_distribution_release }} main"
      file: "deb-src-varnish"
