---

- name: Setup varnish repository key
  apt_key:
    url: https://packagecloud.io/varnishcache/varnish5/gpgkey
    state: present

- name: Setup varnish repository
  apt_repository:
    repo: "{{ item.repo }}"
    file: "{{ item.file }}"
    state: present
  with_items:
    - repo: deb https://packagecloud.io/varnishcache/varnish5/ubuntu/ {{ ansible_distribution_release }} main
      file: deb-varnish
    - repo: deb-src https://packagecloud.io/varnishcache/varnish5/ubuntu/ {{ ansible_distribution_release }} main
      file: deb-src-varnish
