---

- name: reload systemd-unit
  systemd:
    daemon_reload: yes

- name: disable default varnish
  systemd:
    name: varnish
    state: stopped
    enabled: false

- name: disable default varnishlog
  systemd:
    name: varnishlog
    state: stopped
    enabled: false

- name: disable default varnishncsa
  systemd:
    name: varnishncsa
    state: stopped
    enabled: false

- name: restart varnish
  systemd:
    name: varnish@{{ item.name }}
    state: restarted
    enabled: true
  with_items:
    - "{{ varnish_application }}"

- name: stop varnishlog
  systemd:
    name: varnishlog@{{ item.name }}
    state: stopped
    enabled: false
  with_items:
    - "{{ varnish_application }}"

- name: start varnish
  systemd:
    name: varnish@{{ item.name }}
    state: started
    enabled: true
  with_items:
    - "{{ varnish_application }}"
    
- name: unzip consul-template
  unarchive:
    remote_src: yes
    src: /tmp/consul-template.zip
    dest: /usr/local/bin/consul-template
    owner: "root"
    group: "root"
    mode: "0755"
