---

- name: reload systemd-unit
  systemd:
    daemon_reload: yes

- name: disable varnish
  systemd:
    name: varnish
    state: stopped
    enabled: false

- name: restart varnish
  systemd:
    name: varnish-{{ item.name }}.service
    state: restarted
    enabled: true
  with_items:
    - "{{ varnish_application }}"

- name: start varnish
  systemd:
    name: varnish-{{ item.name }}.service
    state: started
    enabled: true
  with_items:
    - "{{ varnish_application }}"
