---

- name: run the main role
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  roles:
    - {role: ansible-varnish}
  vars:
    use_consul: false
    consul_server_address: 127.0.0.1
